import type { Metadata } from "next";
import { Cormorant, Geist, Geist_Mono } from "next/font/google";
import "@/styles/global.scss";
import "@/styles/bootstrap/bootstrap-grid.scss";
import Cursor from "@/components/cursor/Cursor";
import localFont from "next/font/local";

const GNU = localFont({
  src: "./fonts/GNUGrotesk-VF.ttf",
  variable: "--font-gnu",
  display: "swap",
});

const cormorant = Cormorant({
  variable: "--font-cormorant",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cormorant.variable} ${GNU.variable}`}>
        <Cursor />
        {children}
      </body>
    </html>
  );
}
